### ISSUE TITLE
FDC1004 returns FFFF FFFF

### ISSUE THREAD

**Issue by akshayghadage** [beshaya/FDC1004#1]
HI beshaya,

This code is very useful to start with FDC1004 as there is very little documentation available on net for FDC1004. The issue i am now facing is my device always return FFFF FFFF as a raw data. could you Please help me out in detecting where it is going wrong. I am using it with arduino Pro mini atmega328.
I have tried different chips of FDC1004. result is still same.

Thanks in advance.
Akshay Ghadage

**Comment by beshaya** [comment]
Hi Akshay,

Getting all FF's as a response generally means that the FDC1004 isn't
responding at all (since I2C uses pullup resistors, the lines default to
high). If I were you, I'd double check my wiring (SDA to SDA, SCL to SCL,
etc.), then check the values of any pullup resistors you are using (should
be 10k or more). Are there any other devices on the I2C bus?

Just to double check, are you using a 3.3V arduino? The FDC1004 is a 3.3
volt chip, and it should be possible to get it to work with a 5V arduino,
but I've never tried.

If everything checks out, try running an I2C scan sketch, like this one:
http://playground.arduino.cc/Main/I2cScanner. You should get a response
from the FDC1004's I2C address, 0x50.

**Comment by akshayghadage** [comment]
Thank you very much for reply beshaya. I checked SDA,SCL connection and i am using 5V arduino with 3.3V 10K pull up as SDA,SCL are open drain connection. I run I2C scanner sketch and it detect this address 80 of FDS1004 as there are no other connection in I2C bus. But still it returns either FFFF FFFF as output or hung few times. When it hung SCL pin pulled low and remains in low state.  And your right FDC doesn't respond as there is no excitation voltage on any CIN channel.

Is there anything i am missing?.

**Comment by beshaya** [comment]
Interesting; could you send me your schematic? Address 80 = 0x50, which is
correct. Do you have a 3.3V arduino you can test with?

**Comment by akshayghadage** [comment]
Hi Benjamin,

Here is my schematic. And i will try to use it with 3.3v Arduino board. The
pull up resistor in Texas Instruments evaluation module is 3.9k so i tried
to vary it from 1k to 20k but still stuck.

**Comment by akshayghadage** [comment]
Hi Benjamin,

Issue is resolved. With the help of your code i write simple code for repeated conversion mode and reading continuously and it worked. I don't know exact reason but after debugging a lot i found FDC1004 didn't work well when used in disabled repeated mode but working fine with repeated mode. Thank you very much..your code helped a lot...:-)
