### ISSUE TITLE
Invalid number of fF for each bit in CAPDAC

### ISSUE THREAD

**Issue by jomag** [beshaya/FDC1004#5]
FEMTOFARADS_CAPDAC is set to 3028. I think there is two problems with that:

First, I guess you got that value by reading the data sheet: the max value of the capdac is 96.875. 5 bits = 32 steps so 1 bit is 96.875 / 32 = 3.02734375. Multiply by 1000 and you have **3027**, not 3028. Right? Or is there a reason why you round up?

But I think you miss that the max value of CAPDAC is 31, not 32. The data sheet says Coffset = CAPDAC \* 3.125. And it adds up: the max value of CAPDAC is 11111b = 31 so the max offset is 31 \* 3.125 = 96.875.

So if I'm not mistaken FEMTOFARADS_CAPDAC should be 3125.

**Comment by jomag** [comment]
Another thing: how did you get to the ATTOFARADS_UPPER_WORD value of 457?

According to the data sheet:

Capacitance in pF = measurement / 2^19 + C_offset

If I understand the documentation correctly the measurement is 24 bit and the 8 LSB of LSB_MEASn should be thrown away. So:

raw measurement = (MSB << 8) | (LSB >> 8)

As you say the LSB can be ignored since it's mostly noice.

That means that the least significant bit of MSB is (1 << 8) / 2^19 pF = 488 aF. This is in the same neighbourhood as your constant (457). How did you get to that value?

**Comment by beshaya** [comment]
jomag,

Thanks for looking at this so closely. Its been a while since I wrote this library, so I can only guess at how I calculated what I did. This definitely explains why I got some values that seemed a little off when I was originally using it...

> First, I guess you got that value by reading the data sheet: the max value of the capdac is 96.875.

The datasheet actually lists the max value of the capdac as 96.9. I see that it was changed in October 2014. Given that 96.875 divides out so well, I'm going to guess that is what it is supposed to be.

> But I think you miss that the max value of CAPDAC is 31, not 32.

Good catch. Will adjust

I should also pass on the warning of a TI rep: the FDC1004 is a +/-15pF device; the capdac is not accurate enough to give high resolution readings relative to 0pF (i.e. you only get the listed accuracy of the device when CAPDAC is constant)

> Capacitance in pF = measurement / 2^19 + C_offset

I think I missed that line, and computed it from the table: ((15pF - -15pF) / 2 ^ 16) = 457aF.

Again, thanks for catching these!
